.\" Copyright (c) 2025 Mattia Cabrini
.\" SPDX-License-Identifier: GFDL-1.3-only

.TH game_assert 7 2025-09-22 "CMC-Chess Source Code Man-Pages pre-release"

.SH NAME
game_assert \- Assert command format.

.SH SYNOPSIS

=assert assert-kind src=XN dst=XN whence=XN piece=[-]N turn=[-]N

.P
XN \- Coordinate literal (e.g. A1, B8, H3, ...)

.P
N \- A digit

.SH SEE ALSO

.B cmc-chess(6), game_assert(3)
